title = "VRLib"

gitRepoUrl = "https://github.com/raphtalia/VRLib"
gitSourceBranch = "main"

[[classOrder]]
classes = ["VRLib", "Headset", "VRCamera", "LaserPointer", "Hand"]
section = "VRLib"

[[classOrder]]
classes = ["Quest2Controller", "Quest2ControllerAdornee"]
section = "Quest 2"

[[classOrder]]
classes = ["Panel", "TrackingBehavior"]
section = "UI"

[[classOrder]]
classes = ["Button", "Trigger", "Thumbstick"]
section = "Inputs"

[home]
enabled = true
includeReadme = true

[footer]
copyright = "Copyright © 2022 raphtalia"
