title = "VRLib"

gitRepoUrl = "https://github.com/raphtalia/VRLib"
gitSourceBranch = "main"

classOrder = [
  "VRLib",
  "Headset",
  "VRCamera",
  "LaserPointer",
  "Quest2Controller",
  "Quest2ControllerAdornee",
  "Button",
  "Trigger",
  "Thumbstick",
  "Panel",
  "Hand",
  "TrackingBehavior",
]

[home]
enabled = true
includeReadme = true

[footer]
copyright = "Copyright © 2022 raphtalia"
